name: ESLint action

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Installs all the packages
    - name: Install dependencies and packages
      run: npm install

    # Runs the lint script
    - name: Run the lint Script
      run: npm run lint